### PR TITLE
feature: this module can now be built as a "dynamic module" with NGIN…

### PR DESCRIPTION
**Pull request by hnakamur**
…X 1.9.11+ via the --add-dynamic-module=PATH option of ./configure.

I copied codes from the `config` file from
https://github.com/openresty/lua-nginx-module/commit/4f2954302ce642a6f17255cff294663aa6552d8d
and modified it for lua-upstream-cache-nginx-module.

### CODE REVIEW

**Comment by hnakamur** [comment]
@agentzh Could you review this pull request? Thanks!

**Comment by agentzh** [comment]
Sorry, I never maintain this module and I don't think anybody does. This project is dead AFAIK.

**Comment by hnakamur** [comment]
Oh, I see.
Could you add `(DEPRECATED)` or something to the project explanation and update the `Status` in the README?
Thanks!

**Comment by agentzh** [comment]
Sorry, I don't think I have enough GitHub permission to do that.

**Comment by hnakamur** [comment]
Alright. Thanks anyway.
By the way, I use the lua-nginx-module and it is wonderful!
Thanks for creating and sharing a useful software like that!

**Pull request closed without merging**
